
SELECT *
FROM PortfolioProject..CovidDeaths
WHERE CONTINENT IS NOT NULL
ORDER BY 3,4

-- SELECT *
--FROM CovidVaccinations
--ORDER BY 3,4
 

-- select data the we will use

SELECT Location, Date, Total_cases, 
new_cases, total_deaths, population
FROM CovidDeaths

--LOOKING AT TOTAL CASES VS TOTAL DEATHS
-- WHOS COVID DEATH RATE  in country

SELECT Location, Date, Total_cases, total_deaths, 
ROUND((TOTAL_DEATHS/total_cases)*100, 3) AS DeathPercentage
FROM PortfolioProject..CovidDeaths
WHERE Location LIKE '%states'
ORDER BY 1,2

-- looking at the total cases vs population
--SHOWS PERCENTAGE OF INFECTIONS

SELECT Location, Date, Total_cases, population,
ROUND((total_cases/population)*100,3) as infection_rate
FROM CovidDeaths
WHERE LOCATION LIKE '%STATES'
ORDER BY 1,2

--looking at highest infection rate compared to population by country

SELECT Location, MAX(Total_cases) HighestInfectionCount, population,
ROUND(MAX((total_cases/population))*100,3) as infection_rate
FROM portfolioproject..CovidDeaths
--WHERE LOCATION LIKE '%STATES'
GROUP BY population, location
ORDER BY 1,2

-- showing most deaths per population by country

--DEATHS BY CONTINENT 

SELECT continent, MAX(CAST(total_deaths as int)) TotalDeathsCount
FROM PortfolioProject..CovidDeaths
--WHERE LOCATION LIKE '%STATES'
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TotalDeathsCount desc

-- GLOBAL NUMBERS

SELECT SUM(new_cases) as total_cases, SUM(CAST(new_deaths as int)) as total_deaths,
SUM(CAST(new_deaths as int))/SUM(new_cases)*100 as death_percentage
FROM PortfolioProject..CovidDeaths
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

-- TOTAL POPULATION VS VACCINATED


SELECT DEA.CONTINENT,DEA.LOCATION, DEA.DATE,DEA.POPULATION,VAC.new_vaccinations
, SUM(CAST(VAC.new_vaccinations AS BIGINT))  OVER 
(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)AS ROLLINGVACCINATIONS
, (ROLLINGVACCINATIONS/POPULATION*100
FROM PortfolioProject..COVIDDEATHS DEA
JOIN PortfolioProject..CovidVaccinations VAC
ON DEA.LOCATION=VAC.location
AND DEA.DATE=VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL AND DEA.LOCATION LIKE '%STATES'
ORDER BY 2,3

--CTE

WITH POPVSVAC (CONTINENT, LOCATION, DATE, POPULATION, new_vaccination, ROLLINGVACCINATIONS)
AS 
(
SELECT DEA.CONTINENT,DEA.LOCATION, DEA.DATE,DEA.POPULATION,VAC.new_vaccinations
, SUM(CAST(VAC.new_vaccinations AS BIGINT))  OVER 
(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)AS ROLLINGVACCINATIONS
 --(ROLLINGVACCINATIONS/POPULATION)*100
FROM PortfolioProject..COVIDDEATHS DEA
JOIN PortfolioProject..CovidVaccinations VAC
ON DEA.LOCATION=VAC.location
AND DEA.DATE=VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL 
--ORDER BY 2,3
)
SELECT *,(ROLLINGVACCINATIONS/POPULATION)*100
FROM POPVSVAC


--TEMP TABLE
DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
ROLLINGVACCINATIONS NUMERIC
)
INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT DEA.CONTINENT,DEA.LOCATION, DEA.DATE,DEA.POPULATION,VAC.new_vaccinations
, SUM(CAST(VAC.new_vaccinations AS BIGINT))  OVER 
(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)AS ROLLINGVACCINATIONS
 --(ROLLINGVACCINATIONS/POPULATION)*100
FROM PortfolioProject..COVIDDEATHS DEA
JOIN PortfolioProject..CovidVaccinations VAC
ON DEA.LOCATION=VAC.location
AND DEA.DATE=VAC.DATE
--WHERE DEA.CONTINENT IS NOT NULL 
--ORDER BY 2,3

SELECT *,(ROLLINGVACCINATIONS/POPULATION)*100
FROM #PERCENTPOPULATIONVACCINATED


-- CREATING VIEW FOR DATA VIZUALTISATION

CREATE VIEW PERCENTPOPULATIONVACCINATED AS 
SELECT DEA.CONTINENT,DEA.LOCATION, DEA.DATE,DEA.POPULATION,VAC.new_vaccinations
, SUM(CAST(VAC.new_vaccinations AS BIGINT))  OVER 
(PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)AS ROLLINGVACCINATIONS
 --(ROLLINGVACCINATIONS/POPULATION)*100
FROM PortfolioProject..COVIDDEATHS DEA
JOIN PortfolioProject..CovidVaccinations VAC
ON DEA.LOCATION=VAC.location
AND DEA.DATE=VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL 
--ORDER BY 2,3

















SELECT DISTINCT continent, LOCATION
FROM PortfolioProject..CovidDeaths
GROUP BY CONTINENT, LOCATION
ORDER BY CONTINENT







SELECT LOCATION, COUNT(LOCATION) NUMRECORDS
FROM COVIDDEATHS
GROUP BY LOCATION
ORDER BY 2 DESC